site_name: Radia Perlman - Turma 2 - 2025.2
site_description: "Projeto da disciplina FGA315 - Qualidade de Software 1: Avaliação da Qualidade da plataforma Oppia."
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T02_Radia_Perlman
repo_name: 2025-2_T02_Radia_Perlman

nav:
  - Introdução: index.md
  - Fase 1 - Requisitos da Avaliação:
      - 1. Propósito e Uso dos Resultados: fase1/01_proposito.md
      - 2. Requisitante e Partes Interessadas: fase1/02_requisitante.md
      - 3. Descrição do Produto de Software: fase1/03_descricao_produto.md
      - 4. Modelo de Qualidade (SQuaRE): fase1/04_modelo_qualidade.md
      - 5. Seleção e Priorização de Características: fase1/05_selecao.md
      - 6. Escopo e Profundidade da Avaliação: fase1/06_escopo.md
      - 7. Vínculo com ODS: fase1/07_ods.md
  - Fase 2 - Especificação da Avaliação:
      - (A ser definido): fase2/placeholder.md
  - Fase 3 - Projeto da Avaliação:
      - (A ser definido): fase3/placeholder.md
  - Fase 4 - Execução da Avaliação:
      - (A ser definido): fase4/placeholder.md

theme:
  name: material
  language: pt
  
  logo: assets/images/logo-unb.png
  favicon: assets/images/logo-unb.png

  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
      primary: indigo
      accent: orange

markdown_extensions:
  - admonition
  - attr_list
  - footnotes  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - stylesheets/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T02_Radia_Perlman
